// gatsby/src/components/Footer.jsx
import * as React from "react";

const Footer = () => {
  return (
    <div className="text-center px-t py-8 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
      Demo by{" "}
      <a
        target="_blank"
        rel="noreferrer noopener"
        href="https://enterspeed.com"
        className="hover:text-blue-800"
      >
        Enterspeed
      </a>
    </div>
  );
};

export default Footer;

// nuxt/components/Footer.vue
<template>
  <div
    className="
      text-center
      px-t
      py-8
      mx-auto
      sm:max-w-xl
      md:max-w-full
      lg:max-w-screen-xl
      md:px-24
      lg:px-8
    "
  >
    Demo by
    <a
      target="_blank"
      rel="noreferrer noopener"
      href="https://enterspeed.com"
      className="hover:text-blue-800"
    >
      Enterspeed
    </a>
  </div>
</template>;
